"""Build figures/algorithms.tex (LaTeX, algorithmicx) for Algorithm 1 (codebook-constrained soft decoding) and
Algorithm 2 (calibrated registry attribution).
Every number is read from result files: v3_thresholds.json, extra_E4_summary.json, algo_repro_summary.json, v4_summary.json."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
J = lambda p: json.loads((ROOT / p).read_text(encoding="utf-8"))  # noqa: E731
th = J("reports/analysis/v3_thresholds.json")
e4 = J("reports/analysis/extra_E4_summary.json")["E4"]
rp = J("reports/analysis/algo_repro_summary.json")
proto = J("configs/protocol_v5.json")
lock = J("configs/protocol_v5_lock.json")
tau = th["methods"]["C"]["tau"]
alpha, ncal = th["alpha_cal"], th["n_cal"]
N = len(th["registry"]["BCH16_ids"])
dec_ms = e4["stages_ms"]["hflip_contrast1.5"]["bch16_soft_decode_all_regions"]["median"]
c = rp["checks"]
a1, a2a, a2b, a2c = c["A1_soft_decoding_reserve"], c["A2a_calibration"], c["A2b_test_acceptance"], c["A2c_region_acceptance_reserve"]
m = a2a["m"]
seeds = proto["execution"]
assert rp["all_pass"]

TEX = r"""% Generated by scripts/figures/build_algorithms.py from result files. Requires \usepackage{algorithm,algpseudocode}.
\begin{algorithm}[t]
\caption{Codebook-constrained soft decoding for WAM multi-message watermarks}\label{alg:decode}
\begin{algorithmic}[1]
\Require image $x$; IDs $u_1,\dots,u_k$ (16-bit, $k\le 5$); WAM embedder $E$ and extractor $D$ (unchanged); region masks $M_1,\dots,M_k$ (WAM \S5.5, 10\% squares); codebook $\mathcal{C}$ = extended BCH(32,16), $|\mathcal{C}|=65{,}536$, $d_{\min}=8$, codewords $c\in\{-1,+1\}^{32}$
\Ensure regions $R_r$ with decoded ID $\hat u_r$ and score $s_r$
\Statex \textit{Embedding}
\For{$j=1,\dots,k$} \State $w_j \gets E\big(x, c(u_j)\big)$ \EndFor
\State $y \gets x\odot(1-\sum_j M_j) + \sum_j w_j\odot M_j$
\Statex \textit{Decoding} ($y'$: $y$ after any distortion)
\State $(p, L) \gets D(y')$ \Comment{$p$: watermark logits, $L\in\mathbb{R}^{32\times H\times W}$: bit logits}
\State $P \gets \{i : \sigma(p_i) > 0.5\}$;\quad $b_i \gets \mathbb{1}[L_i>0]$ for $i\in P$
\State $\{R_r\} \gets \textsc{DBSCAN}\big(\{b_i\};\ \text{Hamming }\varepsilon=1,\ \text{min\_samples}=1000\big)$ \Comment{WAM, unchanged}
\For{each region $R_r$}
  \State $l_r \gets \frac{1}{|R_r|}\sum_{i\in R_r} L_i$
  \State $\hat c_r \gets \arg\max_{c\in\mathcal{C}} \langle c, l_r\rangle$;\quad $s_r \gets \langle \hat c_r, l_r\rangle$ \Comment{one $65{,}536\times 32$ product}
  \State $\hat u_r \gets \mathrm{ID}(\hat c_r)$
\EndFor
\State \Return $\{(R_r,\hat u_r,s_r)\}$
\end{algorithmic}
\end{algorithm}

\begin{algorithm}[t]
\caption{Calibrated registry attribution}\label{alg:attr}
\begin{algorithmic}[1]
\Require registry $U$ ($N=""" + f"{N:,}".replace(",", "{,}") + r"""$); calibration scenes $t=1,\dots,n$ with known embedded IDs ($n=""" + f"{ncal:,}".replace(",", "{,}") + r"""$); level $\alpha=""" + f"{alpha}" + r"""$
\Ensure threshold $\tau$; accepted IDs of a new image
\Statex \textit{Calibration}
\For{$t=1,\dots,n$}
  \State run Algorithm~\ref{alg:decode} $\to \{(\hat u_r, s_r)\}$
  \State $z_t \gets \max\{s_r : \hat u_r\in U,\ \hat u_r \text{ not embedded in scene } t\}$ \Comment{$-\infty$ if empty}
\EndFor
\State $m \gets \lfloor \alpha(n+1)\rfloor - 1$;\quad $\tau \gets$ the $(m+1)$-th largest finite $z_t$ \Comment{$-\infty$ if fewer}
\Statex \textit{Attribution}
\State run Algorithm~\ref{alg:decode} on the new image $\to \{(R_r,\hat u_r, s_r)\}$
\State accept $\hat u_r$ \textbf{iff} $\hat u_r\in U$ \textbf{and} $s_r>\tau$
\Statex \textit{Guarantee} (exchangeable, non-adversarial scenes): $\Pr(\text{false attribution}) \le (m+1)/(n+1) \le \alpha$
\end{algorithmic}
\end{algorithm}
"""

(ROOT / "figures" / "algorithms.tex").write_text(TEX, encoding="utf-8")
print("written figures/algorithms.tex")
